version: "3.2"

services:

  db:
    image: mariadb
    volumes:
      - './volumes/db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: test_usr
      MYSQL_PASSWORD: test_passwd
  
  php:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - './src:/var/www/html'
    environment:
      - APP_UID=1000
      - APP_GID=1000
  
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - './src:/var/www/html'
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
